"""add_avatar_columns

Revision ID: 7e96a3e0fa46
Revises: 3e57f3f694be
Create Date: 2026-06-06 00:15:18.018359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e96a3e0fa46'
down_revision: Union[str, Sequence[str], None] = '3e57f3f694be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linked_accounts', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('github_avatar_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'github_avatar_url')
    op.drop_column('linked_accounts', 'avatar_url')
    # ### end Alembic commands ###
